from datetime import date

from sentinel.models.event import HealthEvent, RiskCategory


def generate_daily_brief(day: date, events: list[HealthEvent]) -> str:
    """Generate a Markdown daily intelligence brief."""
    # Sort by risk score descending
    events_sorted = sorted(events, key=lambda e: e.risk_score, reverse=True)

    critical = [e for e in events_sorted if e.risk_category == RiskCategory.CRITICAL]
    high = [e for e in events_sorted if e.risk_category == RiskCategory.HIGH]
    medium = [e for e in events_sorted if e.risk_category == RiskCategory.MEDIUM]
    low = [e for e in events_sorted if e.risk_category == RiskCategory.LOW]

    lines = [
        f"# SENTINEL Daily Intelligence Brief -- {day.isoformat()}",
        "",
        "## Executive Summary",
        "",
        f"SENTINEL collected and analyzed **{len(events)}** health events today. "
        f"**{len(critical)}** critical, **{len(high)}** high, "
        f"**{len(medium)}** medium, and **{len(low)}** low risk events identified.",
        "",
    ]

    if critical or high:
        lines.append("## Critical & High Risk Events")
        lines.append("")
        for event in critical + high:
            lines.extend(_format_event(event))

    if medium:
        lines.append("## Medium Risk Events")
        lines.append("")
        for event in medium:
            lines.extend(_format_event_brief(event))

    if low:
        lines.append("## Low Risk Events")
        lines.append("")
        lines.append(f"{len(low)} low-risk events collected. See dashboard for details.")
        lines.append("")

    # Source summary
    sources: dict[str, int] = {}
    for e in events:
        sources[e.source] = sources.get(e.source, 0) + 1
    lines.append("## Source Summary")
    lines.append("")
    lines.append("| Source | Events |")
    lines.append("|--------|--------|")
    for source, count in sorted(sources.items()):
        lines.append(f"| {source} | {count} |")
    lines.append("")

    lines.append("---")
    lines.append(f"*Generated by SENTINEL on {day.isoformat()}*")

    return "\n".join(lines)


def _format_event(event: HealthEvent) -> list[str]:
    lines = [
        f"### {event.title} -- Risk: {event.risk_score:.1f} ({event.risk_category})",
        "",
        f"- **Source:** {event.source} | **Disease:** {event.disease} | "
        f"**Countries:** {', '.join(event.countries)}",
        f"- **Swiss Relevance:** {event.swiss_relevance:.1f}",
        f"- **Operations:** {event.operational_priority} | Lead: {event.lead_agency} | "
        f"Decision Window: {event.decision_window_hours}h",
        f"- **Playbook:** {event.playbook} | SLA: {event.playbook_sla_hours}h | "
        f"Escalation: {event.escalation_level}",
        f"- **Provenance:** {len(event.source_evidence)} sources | "
        f"Graph: {event.provenance_hash}",
    ]
    if event.case_count:
        lines.append(
            f"- **Cases:** {event.case_count}"
            + (f" | **Deaths:** {event.death_count}" if event.death_count else "")
        )
    if event.analysis:
        lines.append(f"- **Analysis:** {event.analysis[:500]}")
    if event.one_health_tags:
        lines.append(f"- **Tags:** {', '.join(event.one_health_tags)}")
    if event.recommended_actions:
        lines.append(f"- **Priority Action:** {event.recommended_actions[0]}")
    lines.extend(["", f"[Source]({event.url})", ""])
    return lines


def _format_event_brief(event: HealthEvent) -> list[str]:
    return [
        f"- **{event.title}** -- {event.disease} in {', '.join(event.countries)} "
        f"(Risk: {event.risk_score:.1f}, Swiss Relevance: {event.swiss_relevance:.1f})",
    ]
